### PR TITLE
Upgrade to latest rust

### LINKED ISSUE #340: Compiler error
I don't know if it's because I'm on a newer version of rust, but when compiling this I get this:

```
/Users/reed/.cargo/git/checkouts/event-2a5e8fafd77d1cdc/master/src/generic_event.rs:176:17: 176:47 error: type annotations required: cannot resolve `update::UpdateEvent : core::marker::MarkerTrait` [E0283]
/Users/reed/.cargo/git/checkouts/event-2a5e8fafd77d1cdc/master/src/generic_event.rs:176                 TypeId::of::<Box<UpdateEvent>>()
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/reed/.cargo/git/checkouts/event-2a5e8fafd77d1cdc/master/src/generic_event.rs:176:17: 176:47 note: required because of the requirements on the impl of `core::marker::Reflect` for `Box<update::UpdateEvent>`
/Users/reed/.cargo/git/checkouts/event-2a5e8fafd77d1cdc/master/src/generic_event.rs:176                 TypeId::of::<Box<UpdateEvent>>()
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/reed/.cargo/git/checkouts/event-2a5e8fafd77d1cdc/master/src/generic_event.rs:176:17: 176:47 note: required by `core::any::TypeId::of`
/Users/reed/.cargo/git/checkouts/event-2a5e8fafd77d1cdc/master/src/generic_event.rs:176                 TypeId::of::<Box<UpdateEvent>>()
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by Potpourri**
close #340

### CODE REVIEW

**Comment by bvssvni** [comment]
Thanks!

**Comment by rweichler** [comment]
I think this broke compatibility with https://github.com/PistonDevelopers/camera_controllers

```
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:145:11: 148:11 error: type `&E` does not implement any method in scope named `update`
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:145         e.update(|args| {
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:146             let cam = self.camera(args.dt);
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:147             self.position = cam.position;
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:148         });
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:148:11: 148:11 help: methods from traits can only be called if the trait is implemented and in scope; the following traits define a method `update`, perhaps you need to implement one of them:
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:148:11: 148:11 help: candidate #1: `event::update::UpdateEvent`
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:148:11: 148:11 help: candidate #2: `event_loop::EventMap`
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:146:35: 146:42 error: the type of this value must be known in this context
/Users/reed/.cargo/git/checkouts/camera_controllers-2599202511a08758/master/src/first_person.rs:146             let cam = self.camera(args.dt);
                                                                                                                                      ^~~~~~~
```

**Comment by Potpourri** [comment]
Thanks for report I'll fix it soon.

**Comment by rweichler** [comment]
np. I'd fix it myself, but I'm using this to learn Rust and I have no idea what any of this does yet haha

**Comment by Potpourri** [comment]
I updated camera_controllers. Now should work.

**Pull request merged**
